server:
  port: 8081
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: UTF-8

age: 19
name: zhaodabao

personinfo:
  name: zhaoxiaobao
  age: 3

test:
  objname: thisisaname
  prop1: prop1
  personlist:
    - name: aaa
      age: 1
    - name: bbb
      age: 2
    - name: ccc
      age: 3

personlist:
  - name: aaaaaa
    age: 11
  - name: bbbbbb
    age: 22
  - name: cccccc
    age: 33
