spring:
  datasource:
    url: jdbc:mariadb://192.168.56.102:3306/Test
    username: Test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false
server:
  port: 8080